version: "3.8"

services:
  sentiment-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    restart: always
